-- ============================================================
-- OPR Hero Customizer — Global script (hand-maintained template,
-- no generator). Star Quest / hero-scale: Quality/Defense/Tough plus
-- Power and Str/Dex/Wil.
--
-- Unlike opr_hero_assigner.lua (which bakes one fixed stat block per
-- hero and goes stale as soon as heroes level up), this assigns a
-- generic "HERO NAME" template that you then edit IN-GAME from the
-- model's own right-click menu — no regenerating between missions.
--
-- What this does:
--   - Right-click any unassigned model -> "Assign Hero Template".
--     Assignment INJECTS a self-contained script into that model
--     (via setLuaScript + reload), so the model keeps working even if
--     you save it individually and load it into a different game with
--     no Global script at all.
--   - An assigned hero's own right-click menu has:
--       Take Wound / Heal Wound, Use Power / Restore Power
--         (applied to your whole current selection)
--       Measure Range
--       Ability Info...  -> pick an ability (or all) to print its
--         description to your chat; the tooltip shows names only
--       Edit Hero...  -> a list of edits (name, class/level, stats,
--         max Tough/Power, equipment, add/edit/remove abilities,
--         restore to full). Applies to the right-clicked model only.
--   - Everything you edit is stored in the model's own saved state
--     (onSave), so it persists with the object across saves, copies,
--     and saved-object loads.
--   - Heroes assigned with an OLDER version of this file are upgraded
--     to the current per-model script automatically (keeping all their
--     data) when this Global script loads or when they're spawned.
--
-- Install:
--   Modding -> Scripting -> Global, select all and delete whatever is
--   there, paste this in, then Save & Play. Chat should then show
--   "Hero Customizer Global loaded (script vN)" with the version you
--   pasted. If it doesn't, TTS is still running the previous Global
--   script (newly assigned models get the old per-model script and
--   upgrades don't happen): make sure you copied the latest file
--   (refresh the page you copy from) and Save & Play again. The
--   "Error no save found" message on its own is harmless.
--
-- Defaults:
--   HERO_DEFAULTS below is what a freshly assigned model starts with.
--   Edit it if you want different starting values; models that are
--   already assigned keep their own values.
-- ============================================================

-- Set true if you only want the menu added to objects tagged
-- "Figurine" (most official minis/tokens carry that tag).
local ONLY_FIGURINES = false

local HERO_DEFAULTS = {
  name = "HERO NAME",
  class = "",   -- e.g. "Instigator" (Class/Level line hidden while empty)
  level = 1,
  quality = 4,  -- Q4+
  defense = 4,  -- D4+
  str = 4,
  dex = 4,
  wil = 4,
  toughMax = 3, -- 0 hides Tough and its menu items
  powMax = 3,   -- 0 hides Power and its menu items
  equipment = "CCW (A1)", -- comma-separated, e.g. 'Pistol (12", A1), CCW (A1)'
  abilities = {
    -- { name = "Example Ability", desc = "What it does." },
  },
}

-- Escapes a string so it's safe to drop into a Lua "..." literal
-- inside the per-model script template.
local function luaStringEscape(s)
  s = s:gsub("\\", "\\\\")
  s = s:gsub('"', '\\"')
  s = s:gsub("\n", "\\n")
  s = s:gsub("\r", "\\r")
  return s
end

-- Escapes a string so gsub treats it as literal replacement text
-- rather than interpreting "%" as a capture-group reference.
local function gsubSafe(s)
  return (s:gsub("%%", "%%%%"))
end

-- Turns HERO_DEFAULTS into a Lua table literal for the per-model
-- script. Handles only what HERO_DEFAULTS uses: strings, numbers,
-- booleans, arrays, and tables with identifier keys.
local function serialize(v)
  local t = type(v)
  if t == "string" then
    return '"' .. luaStringEscape(v) .. '"'
  elseif t == "number" or t == "boolean" then
    return tostring(v)
  elseif t == "table" then
    local parts = {}
    if #v > 0 or next(v) == nil then
      for _, x in ipairs(v) do table.insert(parts, serialize(x)) end
    else
      local keys = {}
      for k, _ in pairs(v) do table.insert(keys, k) end
      table.sort(keys)
      for _, k in ipairs(keys) do
        table.insert(parts, k .. " = " .. serialize(v[k]))
      end
    end
    return "{ " .. table.concat(parts, ", ") .. " }"
  end
  return "nil"
end

-- ===== Self-contained per-model script template =====
-- Everything an assigned hero needs to run entirely on its own. The
-- only placeholder is @@DEFAULTS@@, filled from HERO_DEFAULTS; all
-- later edits live in the model's saved state, not in this script.

local PER_MODEL_SCRIPT_TEMPLATE = [==[
-- Self-contained OPR hero script — generated by opr_hero_customizer.lua
-- opr_hero_customizer script version: @@VERSION@@
-- Portable: this object keeps working (name, tooltip, wound/power
-- tracking, in-game editing) even when saved individually and loaded
-- into a different game, because everything it needs lives in this
-- script and its saved state.

-- Starting values, used only until the first edit is saved. (When
-- the Global script upgrades an older copy of this script, it puts
-- that hero's current data here, so nothing is lost.)
local DEFAULTS = @@DEFAULTS@@

-- Current hero data: DEFAULTS' fields plus current tough/pow.
local state

-- ===== Text helpers =====
-- NOTE: TTS runs Lua on MoonSharp, which throws "pattern too complex"
-- on lazy-match patterns like "^(.-)literal(.+)$" over longer strings
-- (standard Lua doesn't). Everything below uses plain find()/sub() and
-- simple non-lazy patterns instead.

local function trim(s)
  s = s:gsub("^%s+", "")
  s = s:gsub("%s+$", "")
  return s
end

-- Splits a comma-separated string on TOP-LEVEL commas only, so a
-- weapon like "Energy Sword (A6, AP(1), Rending)" stays one item
-- instead of shattering on the commas inside its own parentheses.
local function splitTopLevelCommas(s)
  local items = {}
  local depth = 0
  local start = 1
  for i = 1, #s do
    local c = s:sub(i, i)
    if c == "(" then depth = depth + 1
    elseif c == ")" then depth = depth - 1
    elseif c == "," and depth == 0 then
      table.insert(items, s:sub(start, i - 1))
      start = i + 1
    end
  end
  table.insert(items, s:sub(start))
  for i, item in ipairs(items) do
    items[i] = trim(item)
  end
  return items
end

-- Splits text on newlines with plain find() (no pattern).
local function splitLines(text)
  local lines = {}
  local pos = 1
  while true do
    local nlIdx = text:find("\n", pos, true)
    if not nlIdx then
      table.insert(lines, text:sub(pos))
      break
    end
    table.insert(lines, text:sub(pos, nlIdx - 1))
    pos = nlIdx + 1
  end
  return lines
end

-- Parses "Name: description" lines (one ability per non-blank line;
-- description optional) into {name, desc} entries.
local function parseAbilityLines(text)
  local result = {}
  for _, line in ipairs(splitLines((text or ""):gsub("\r", ""))) do
    line = trim(line)
    if line ~= "" then
      local colonIdx = line:find(":", 1, true)
      if colonIdx then
        table.insert(result, {
          name = trim(line:sub(1, colonIdx - 1)),
          desc = trim(line:sub(colonIdx + 1)),
        })
      else
        table.insert(result, { name = line, desc = "" })
      end
    end
  end
  return result
end

local function abilityToLine(a)
  if a.desc ~= "" then return a.name .. ": " .. a.desc end
  return a.name
end

-- Accepts "4", "4+", " 4 " -> 4. Returns nil for anything that isn't
-- a whole number.
local function parseInt(text)
  local t = trim(text or "")
  if t:sub(-1) == "+" then t = trim(t:sub(1, -2)) end
  local n = tonumber(t)
  if not n or n ~= math.floor(n) then return nil end
  return math.floor(n)
end

-- ===== State =====

local function toInt(v, fallback)
  local n = tonumber(v)
  if not n then return fallback end
  return math.floor(n)
end

local function toStr(v, fallback)
  if type(v) == "string" then return v end
  if type(v) == "number" then return tostring(v) end
  return fallback
end

-- Builds a complete, sane state from saved data (or {} on first
-- load), falling back to DEFAULTS field by field.
local function normalizeState(src)
  local s = {}
  s.name = toStr(src.name, DEFAULTS.name)
  s.class = toStr(src.class, DEFAULTS.class)
  s.level = toInt(src.level, DEFAULTS.level)
  s.quality = toInt(src.quality, DEFAULTS.quality)
  s.defense = toInt(src.defense, DEFAULTS.defense)
  s.str = toInt(src.str, DEFAULTS.str)
  s.dex = toInt(src.dex, DEFAULTS.dex)
  s.wil = toInt(src.wil, DEFAULTS.wil)
  s.toughMax = math.max(0, toInt(src.toughMax, DEFAULTS.toughMax))
  s.powMax = math.max(0, toInt(src.powMax, DEFAULTS.powMax))
  s.tough = math.max(0, math.min(s.toughMax, toInt(src.tough, toInt(DEFAULTS.tough, s.toughMax))))
  s.pow = math.max(0, math.min(s.powMax, toInt(src.pow, toInt(DEFAULTS.pow, s.powMax))))
  s.equipment = toStr(src.equipment, DEFAULTS.equipment)
  local abilitiesSrc = src.abilities
  if type(abilitiesSrc) ~= "table" then abilitiesSrc = DEFAULTS.abilities end
  s.abilities = {}
  for _, a in ipairs(abilitiesSrc) do
    if type(a) == "table" and toStr(a.name, "") ~= "" then
      table.insert(s.abilities, { name = toStr(a.name, ""), desc = toStr(a.desc, "") })
    end
  end
  return s
end

-- ===== Display =====

-- Colored via TTS's own BBCode ([hexcolor]text[-]), which works
-- directly in the Name field and tooltips — no UI panel needed.
-- White text just uses no color tag at all rather than [ffffff].
local CLASS_LEVEL_COLOR = "73CDE0" -- light blue, for "Class LvN"
local Q_COLOR = "ef4444"     -- red-orange, for Quality
local D_COLOR = "0ea5e9"     -- sky blue, for Defense
local TOUGH_COLOR = "2ecc40" -- green, for current and max Tough
local POW_COLOR = "a855f7"   -- purple, for current and max Power
local RULES_COLOR = "3498db" -- blue

-- Name field: bold hero name, then "Class LvN", then Quality/
-- Defense, then "Tough: current / max", then "Power: current / max"
-- — all visible without hovering.
local function buildNameLabel()
  local label = "[b]" .. state.name .. "[/b]"
  if state.class ~= "" then
    label = label ..
      "\n[" .. CLASS_LEVEL_COLOR .. "]" .. state.class .. "[-] Lv" .. state.level
  end
  label = label ..
    "\n[" .. Q_COLOR .. "][b]Q" .. state.quality .. "[/b]+[-]" ..
    " / " ..
    "[" .. D_COLOR .. "][b]D" .. state.defense .. "[/b]+[-]"
  if state.toughMax > 0 then
    label = label ..
      "\n[b]Tough: [" .. TOUGH_COLOR .. "]" .. state.tough .. "[/b][-]" ..
      " / " ..
      "[b][" .. TOUGH_COLOR .. "]" .. state.toughMax .. "[/b][-]"
  end
  if state.powMax > 0 then
    label = label ..
      "\n[b]Power: [" .. POW_COLOR .. "]" .. state.pow .. "[/b][-]" ..
      " / " ..
      "[b][" .. POW_COLOR .. "]" .. state.powMax .. "[/b][-]"
  end
  return label
end

local WEAPON_PROFILE_COLOR = "c0c6cf" -- light grey, for a weapon's (range, attacks, ...)

-- Stat tags an ability name can end in, e.g. "Battle Rest (Str)".
-- Tagged abilities are grouped under their stat in the tooltip.
local STAT_TAGS = { "Str", "Dex", "Wil" }

-- Splits "Battle Rest (Str)" into "Battle Rest", "Str". Returns the
-- name unchanged and nil if it doesn't end in one of STAT_TAGS.
-- Plain find()/sub() only (no lazy pattern — see MoonSharp note).
local function splitStatTag(name)
  if name:sub(-1) ~= ")" then return name, nil end
  local openIdx = nil
  local searchFrom = 1
  while true do
    local i = name:find("(", searchFrom, true)
    if not i then break end
    openIdx = i
    searchFrom = i + 1
  end
  if not openIdx then return name, nil end
  local tag = trim(name:sub(openIdx + 1, -2))
  for _, t in ipairs(STAT_TAGS) do
    if tag:lower() == t:lower() then
      return trim(name:sub(1, openIdx - 1)), t
    end
  end
  return name, nil
end

-- "Grave-Chillblain Wand (18\", A4)" -> bullet, white name, then the
-- profile in light grey. Items without parentheses show as-is.
local function formatEquipItem(item)
  local openIdx = item:find("(", 1, true)
  if not openIdx then return "• " .. item end
  local name = trim(item:sub(1, openIdx - 1))
  local profile = item:sub(openIdx + 1)
  if profile:sub(-1) == ")" then profile = profile:sub(1, -2) end
  profile = trim(profile)
  if name == "" then return "• " .. item end
  return "• " .. name .. "  [" .. WEAPON_PROFILE_COLOR .. "]" .. profile .. "[-]"
end

-- Tooltip (hover): Str/Dex/Wil (Q/D/Tough are already in the Name
-- field), abilities grouped by stat tag, then equipment. Ability
-- descriptions are NOT shown here — they're in the "Ability Info..."
-- menu, to keep the tooltip short.
local function formatDescription()
  local lines = {}
  table.insert(lines, "Str " .. state.str .. "+ | Dex " .. state.dex .. "+ | Wil " .. state.wil .. "+")

  if #state.abilities > 0 then
    local groups, untagged = {}, {}
    for _, a in ipairs(state.abilities) do
      local base, tag = splitStatTag(a.name)
      if tag then
        groups[tag] = groups[tag] or {}
        table.insert(groups[tag], base)
      else
        table.insert(untagged, a.name)
      end
    end
    table.insert(lines, "")
    for _, t in ipairs(STAT_TAGS) do
      if groups[t] then
        table.insert(lines, "[b]" .. t .. ":[/b] [" .. RULES_COLOR .. "]" .. table.concat(groups[t], ", ") .. "[-]")
      end
    end
    if #untagged > 0 then
      table.insert(lines, "[" .. RULES_COLOR .. "]" .. table.concat(untagged, ", ") .. "[-]")
    end
  end

  local equip = trim(state.equipment)
  if equip ~= "" then
    table.insert(lines, "")
    for _, item in ipairs(splitTopLevelCommas(equip)) do
      if item ~= "" then table.insert(lines, formatEquipItem(item)) end
    end
  end
  return table.concat(lines, "\n")
end

-- ===== Range measuring =====

-- TTS's default table scale is 1 world unit = 1 inch. If your table/
-- minis use a different scale, adjust this to calibrate.
local INCHES_PER_UNIT = 1

-- Estimates a round base's radius (in inches) from its axis-aligned
-- bounding box: for a circular base the box is a square of side
-- 2*radius in the x/z plane, so this holds up under rotation.
local function getBaseRadiusInches(obj)
  local bounds = obj.getBounds()
  if not bounds or not bounds.size then return 0 end
  return ((bounds.size.x + bounds.size.z) / 4) * INCHES_PER_UNIT
end

-- Base-edge to base-edge distance, not center to center: OPR measures
-- range from the edge of the model's base, so this subtracts both
-- models' estimated base radii from the raw center-to-center distance.
local function getDistanceInches(a, b)
  local pa, pb = a.getPosition(), b.getPosition()
  local dx, dz = pa.x - pb.x, pa.z - pb.z
  local centerDist = math.sqrt(dx * dx + dz * dz) * INCHES_PER_UNIT
  local edgeDist = centerDist - getBaseRadiusInches(a) - getBaseRadiusInches(b)
  return math.max(0, edgeDist)
end

-- Parses this hero's equipment (e.g. `Boss Pistol (12", A2)`,
-- `CCW (A2)`) into {name, range} pairs. range is nil for melee
-- weapons (no `"` value present), which OPR resolves in base contact
-- rather than by range check.
local function getWeaponRanges()
  local weapons = {}
  local equip = trim(state.equipment)
  if equip == "" then return weapons end
  for _, item in ipairs(splitTopLevelCommas(equip)) do
    local openIdx = item:find("(", 1, true)
    local name = item
    local range = nil
    if openIdx then
      name = trim(item:sub(1, openIdx - 1))
      local closeIdx = item:find(")", openIdx, true)
      local inside = item:sub(openIdx + 1, (closeIdx or (#item + 1)) - 1)
      local firstToken = splitTopLevelCommas(inside)[1] or ""
      local quoteIdx = firstToken:find("\"", 1, true)
      if quoteIdx then
        range = tonumber(trim(firstToken:sub(1, quoteIdx - 1)))
      end
    end
    table.insert(weapons, { name = name, range = range })
  end
  return weapons
end

-- Reports this hero's distance to each target and whether each of
-- its ranged weapons can reach it.
local function measureRangeReport(targets)
  local weapons = getWeaponRanges()
  local lines = {}
  for _, target in ipairs(targets) do
    local dist = getDistanceInches(self, target)
    local targetName = target.getName()
    if targetName == "" then targetName = "target" end
    table.insert(lines, state.name .. " -> " .. targetName .. ": " .. string.format("%.1f", dist) .. "\"")
    for _, w in ipairs(weapons) do
      if w.range then
        local status = dist <= w.range and "IN RANGE" or "out of range"
        table.insert(lines, "   " .. w.name .. " (" .. w.range .. "\"): " .. status)
      else
        table.insert(lines, "   " .. w.name .. " (melee)")
      end
    end
  end
  return table.concat(lines, "\n")
end

-- ===== Wounds / Power =====

-- Both global (not local) so other models can invoke them via
-- .call() when you apply Take/Heal Wound or Use/Restore Power to a
-- multi-selected group. Same names as opr_hero_assigner.lua's
-- per-model script, so mixed selections of both kinds still work.
function adjustWound(params)
  local delta = (params and params.delta) or 0
  state.tough = math.max(0, math.min(state.toughMax, state.tough + delta))
  self.setName(buildNameLabel())
end

function adjustPower(params)
  local delta = (params and params.delta) or 0
  state.pow = math.max(0, math.min(state.powMax, state.pow + delta))
  self.setName(buildNameLabel())
end

-- Raising a max keeps the wounds/power already spent (3/3 -> max 4
-- gives 4/4; 1/3 -> max 4 gives 2/4). Lowering a max only clamps the
-- current value down to the new max.
local function setToughMax(n)
  local gain = math.max(0, n - state.toughMax)
  state.toughMax = n
  state.tough = math.max(0, math.min(n, state.tough + gain))
end

local function setPowMax(n)
  local gain = math.max(0, n - state.powMax)
  state.powMax = n
  state.pow = math.max(0, math.min(n, state.pow + gain))
end

-- ===== Menu =====

local buildMenu

-- Re-applies name, tooltip, and menu after any edit (menu too, since
-- a max of 0 hides its Take/Heal or Use/Restore items).
local function refresh()
  self.setName(buildNameLabel())
  self.setDescription(formatDescription())
  buildMenu()
end

local function warn(player_color, msg)
  broadcastToColor(msg, player_color, {1, 0.4, 0.4})
end

-- Text prompt; blank or cancelled input leaves the value unchanged
-- unless allowBlank is set.
local function promptText(player_color, title, current, allowBlank, apply)
  Player[player_color].showInputDialog(title, current, function(text)
    text = trim(text or "")
    if text == "" and not allowBlank then return end
    apply(text)
    refresh()
  end)
end

local function promptInt(player_color, title, current, minValue, apply)
  Player[player_color].showInputDialog(title, tostring(current), function(text)
    local n = parseInt(text)
    if not n or n < minValue then
      warn(player_color, title .. ": \"" .. tostring(text) .. "\" isn't a whole number of at least " .. minValue .. ". Nothing changed.")
      return
    end
    apply(n)
    refresh()
  end)
end

-- Options dialog over the current abilities; calls pick(index).
-- Labels are numbered so two abilities with the same name stay
-- distinguishable.
local function pickAbility(player_color, title, pick)
  if #state.abilities == 0 then
    warn(player_color, state.name .. " has no abilities yet. Use Edit Hero... -> Add Abilities.")
    return
  end
  local labels, indexByLabel = {}, {}
  for i, a in ipairs(state.abilities) do
    local label = i .. ". " .. a.name
    labels[i] = label
    indexByLabel[label] = i
  end
  Player[player_color].showOptionsDialog(title, labels, labels[1], function(text, index)
    local i = indexByLabel[text] or tonumber(index)
    if i and state.abilities[i] then pick(i) end
  end)
end

local function addAbilities(player_color)
  Player[player_color].showMemoDialog(
    "Add abilities to " .. state.name .. " (one per line, as  Name: description)",
    "",
    function(text)
      local added = parseAbilityLines(text)
      if #added == 0 then return end
      for _, a in ipairs(added) do table.insert(state.abilities, a) end
      refresh()
    end)
end

local function editAbility(player_color)
  pickAbility(player_color, "Edit which ability?", function(i)
    Player[player_color].showMemoDialog(
      "Edit ability (Name: description). Extra lines become extra abilities; clear it to leave unchanged.",
      abilityToLine(state.abilities[i]),
      function(text)
        local replacement = parseAbilityLines(text)
        if #replacement == 0 then return end
        table.remove(state.abilities, i)
        for j, a in ipairs(replacement) do
          table.insert(state.abilities, i + j - 1, a)
        end
        refresh()
      end)
  end)
end

local function removeAbility(player_color)
  pickAbility(player_color, "Remove which ability?", function(i)
    table.remove(state.abilities, i)
    refresh()
  end)
end

-- Prints ability descriptions to the clicking player's chat only.
local function showAbilityInfo(player_color)
  local described = {}
  for _, a in ipairs(state.abilities) do
    if a.desc ~= "" then table.insert(described, a) end
  end
  if #described == 0 then
    warn(player_color, state.name .. " has no ability descriptions yet. Add them via Edit Hero... as  Name: description")
    return
  end
  local function printAbility(a)
    printToColor("[b]" .. a.name .. ":[/b] " .. a.desc, player_color, {1, 1, 1})
  end
  local ALL = "All abilities"
  local labels, abilityByLabel = { ALL }, {}
  for i, a in ipairs(described) do
    local label = i .. ". " .. a.name
    table.insert(labels, label)
    abilityByLabel[label] = a
  end
  Player[player_color].showOptionsDialog(state.name .. ": show which ability?", labels, labels[1], function(text, index)
    if text == ALL then
      printToColor("[b]" .. state.name .. "[/b]", player_color, {1, 1, 1})
      for _, a in ipairs(described) do printAbility(a) end
      return
    end
    local a = abilityByLabel[text] or described[(tonumber(index) or 0) - 1]
    if a then printAbility(a) end
  end)
end

local function openEditMenu(player_color)
  local entries = {
    { "Rename (" .. state.name .. ")", function()
      promptText(player_color, "Hero name", state.name, false, function(v) state.name = v end)
    end },
    { "Class (" .. (state.class ~= "" and state.class or "none") .. ")", function()
      promptText(player_color, "Class (leave blank to hide the Class/Level line)", state.class, true, function(v) state.class = v end)
    end },
    { "Level (" .. state.level .. ")", function()
      promptInt(player_color, "Level", state.level, 0, function(n) state.level = n end)
    end },
    { "Quality (" .. state.quality .. "+)", function()
      promptInt(player_color, "Quality (e.g. 4 for Q4+)", state.quality, 1, function(n) state.quality = n end)
    end },
    { "Defense (" .. state.defense .. "+)", function()
      promptInt(player_color, "Defense (e.g. 4 for D4+)", state.defense, 1, function(n) state.defense = n end)
    end },
    { "Str (" .. state.str .. "+)", function()
      promptInt(player_color, "Str", state.str, 1, function(n) state.str = n end)
    end },
    { "Dex (" .. state.dex .. "+)", function()
      promptInt(player_color, "Dex", state.dex, 1, function(n) state.dex = n end)
    end },
    { "Wil (" .. state.wil .. "+)", function()
      promptInt(player_color, "Wil", state.wil, 1, function(n) state.wil = n end)
    end },
    { "Max Tough (" .. state.toughMax .. ")", function()
      promptInt(player_color, "Max Tough (0 hides it)", state.toughMax, 0, setToughMax)
    end },
    { "Max Power (" .. state.powMax .. ")", function()
      promptInt(player_color, "Max Power (0 hides it)", state.powMax, 0, setPowMax)
    end },
    { "Equipment", function()
      promptText(player_color, "Equipment, comma-separated (e.g. Pistol (12\", A1), CCW (A1))", state.equipment, true, function(v) state.equipment = v end)
    end },
    { "Add Abilities", function() addAbilities(player_color) end },
    { "Edit Ability", function() editAbility(player_color) end },
    { "Remove Ability", function() removeAbility(player_color) end },
    { "Restore Tough & Power to full", function()
      state.tough = state.toughMax
      state.pow = state.powMax
      refresh()
    end },
  }
  local labels, fnByLabel = {}, {}
  for i, e in ipairs(entries) do
    labels[i] = e[1]
    fnByLabel[e[1]] = e[2]
  end
  Player[player_color].showOptionsDialog("Edit " .. state.name, labels, labels[1], function(text, index)
    local fn = fnByLabel[text]
    if not fn and entries[tonumber(index) or 0] then fn = entries[tonumber(index)][2] end
    if fn then fn() end
  end)
end

local function forSelectedOrSelf(player_color, fn)
  local selected = Player[player_color].getSelectedObjects()
  if #selected > 0 then
    for _, o in ipairs(selected) do fn(o) end
  else
    fn(self)
  end
end

buildMenu = function()
  self.clearContextMenu()
  if state.toughMax > 0 then
    self.addContextMenuItem("Take Wound", function(player_color)
      forSelectedOrSelf(player_color, function(o)
        o.call('adjustWound', { delta = -1 })
      end)
    end)
    self.addContextMenuItem("Heal Wound", function(player_color)
      forSelectedOrSelf(player_color, function(o)
        o.call('adjustWound', { delta = 1 })
      end)
    end)
  end
  if state.powMax > 0 then
    self.addContextMenuItem("Use Power", function(player_color)
      forSelectedOrSelf(player_color, function(o)
        o.call('adjustPower', { delta = -1 })
      end)
    end)
    self.addContextMenuItem("Restore Power", function(player_color)
      forSelectedOrSelf(player_color, function(o)
        o.call('adjustPower', { delta = 1 })
      end)
    end)
  end
  self.addContextMenuItem("Measure Range", function(player_color)
    local selected = Player[player_color].getSelectedObjects()
    local targets = {}
    for _, o in ipairs(selected) do
      if o.getGUID() ~= self.getGUID() then table.insert(targets, o) end
    end
    if #targets == 0 then
      broadcastToColor("Measure Range: select one or more target models first, then right-click this model and choose Measure Range again.", player_color, {1, 0.4, 0.4})
      return
    end
    broadcastToColor(measureRangeReport(targets), player_color, {1, 1, 1})
  end)
  self.addContextMenuItem("Ability Info...", function(player_color)
    showAbilityInfo(player_color)
  end)
  self.addContextMenuItem("Edit Hero...", function(player_color)
    openEditMenu(player_color)
  end)
end

-- ===== Save / load =====

function onSave()
  return JSON.encode(state)
end

function onLoad(saved_data)
  local loaded = nil
  if saved_data and saved_data ~= "" then
    local ok, decoded = pcall(JSON.decode, saved_data)
    if ok and type(decoded) == "table" then loaded = decoded end
  end
  state = normalizeState(loaded or {})
  refresh()
end
]==]

-- Bump this whenever PER_MODEL_SCRIPT_TEMPLATE changes: heroes carrying
-- an older version are upgraded automatically (keeping their data)
-- the next time this Global script loads or they're spawned.
local SCRIPT_VERSION = 3

-- Keys copied from an old hero's saved data into the upgraded script.
local STATE_KEYS = {
  "name", "class", "level", "quality", "defense", "str", "dex", "wil",
  "toughMax", "powMax", "tough", "pow", "equipment",
}

-- Starting data for the per-model script: HERO_DEFAULTS, overlaid with
-- an existing hero's saved data when upgrading one.
local function buildDefaults(data)
  local d = {}
  for k, v in pairs(HERO_DEFAULTS) do d[k] = v end
  if type(data) ~= "table" then return d end
  for _, k in ipairs(STATE_KEYS) do
    local v = data[k]
    if type(v) == "string" or type(v) == "number" then d[k] = v end
  end
  if type(data.abilities) == "table" then
    d.abilities = {}
    for _, a in ipairs(data.abilities) do
      if type(a) == "table" and type(a.name) == "string" then
        table.insert(d.abilities, {
          name = a.name,
          desc = type(a.desc) == "string" and a.desc or "",
        })
      end
    end
  end
  return d
end

local function buildPerModelScript(data)
  local script = PER_MODEL_SCRIPT_TEMPLATE
  script = script:gsub("@@VERSION@@", tostring(SCRIPT_VERSION))
  script = script:gsub("@@DEFAULTS@@", gsubSafe(serialize(buildDefaults(data))))
  return script
end

-- Returns the customizer script version an object carries (1 for the
-- first release, which had no version line), or nil if its script
-- isn't one of ours. Plain find() only (MoonSharp pattern limits).
local CUSTOMIZER_MARKER = "generated by opr_hero_customizer.lua"
local VERSION_MARKER = "-- opr_hero_customizer script version: "

local function getCustomizerVersion(script)
  if not script or not script:find(CUSTOMIZER_MARKER, 1, true) then return nil end
  local idx = script:find(VERSION_MARKER, 1, true)
  if not idx then return 1 end
  return tonumber(script:match("^%d+", idx + #VERSION_MARKER)) or 1
end

-- ===== Assignment =====

local function assignTemplate(obj)
  obj.setLuaScript(buildPerModelScript(nil))
  obj.reload()
end

-- Replaces an older customizer script with the current one. The hero's
-- data is read from its saved state and baked in as the new script's
-- starting values, so it survives even if TTS drops the saved state
-- across the reload.
local function upgradeHero(obj, fromVersion)
  local data = nil
  local okState, saved = pcall(function() return obj.script_state end)
  if okState and type(saved) == "string" and saved ~= "" then
    local okDecode, decoded = pcall(JSON.decode, saved)
    if okDecode and type(decoded) == "table" then data = decoded end
  end
  local heroName = (data and type(data.name) == "string") and data.name or "a hero"
  obj.setLuaScript(buildPerModelScript(data))
  obj.reload()
  -- "(data carried by TTS)" = saved state wasn't readable up front, so
  -- the hero's data relies on TTS keeping it across the reload.
  print("Hero Customizer: updated " .. heroName .. " from script v" .. fromVersion ..
    " to v" .. SCRIPT_VERSION .. (data and "." or " (data carried by TTS)."))
end

local function forSelectedOrSelf(player_color, fallbackObj, fn)
  local selected = Player[player_color].getSelectedObjects()
  if #selected > 0 then
    for _, o in ipairs(selected) do fn(o) end
  else
    fn(fallbackObj)
  end
end

-- ===== Menu wiring / upgrades =====
-- Unscripted models get the "Assign Hero Template" menu. Models with an
-- older customizer script are upgraded. Anything else with a script
-- (opr_hero_assigner.lua heroes, workshop objects) is left alone.

local function handleObject(object)
  if ONLY_FIGURINES and not object.hasTag("Figurine") then return end
  local existingScript = object.getLuaScript()
  if existingScript and existingScript ~= "" then
    local version = getCustomizerVersion(existingScript)
    if version and version < SCRIPT_VERSION then
      local ok, err = pcall(upgradeHero, object, version)
      if not ok then
        print("Hero Customizer: update from script v" .. version .. " failed: " .. tostring(err))
      end
    end
    return
  end

  object.clearContextMenu()
  object.addContextMenuItem("Assign Hero Template", function(player_color)
    forSelectedOrSelf(player_color, object, function(o)
      -- Skip already-assigned models in a mixed selection so their
      -- edits aren't wiped back to defaults.
      local s = o.getLuaScript()
      if s == nil or s == "" then assignTemplate(o) end
    end)
  end)
end

-- Covers models already on the table when the save loads. Delayed
-- slightly so it runs after TTS has finished loading every object
-- (and applying any per-object scripts from the scripting editor),
-- rather than racing it.
function onLoad()
  -- Confirms in chat which version is actually running (the editor
  -- can show newer text than TTS is running if Save & Play failed).
  print("Hero Customizer Global loaded (script v" .. SCRIPT_VERSION .. ").")
  Wait.time(function()
    for _, obj in ipairs(getAllObjects()) do
      handleObject(obj)
    end
  end, 0.5)
end

-- ...and models spawned afterward (from a bag, spawnObject, etc.)
function onObjectSpawn(object)
  handleObject(object)
end
