#!/usr/bin/env bash
set -euo pipefail

# ==============================================================
# opr_list_to_lua.sh
#
# Parses an OPR Army Forge text export and generates a Global script
# with UNIT_PROFILES pre-filled from the list, instead of you typing
# every unit in by hand.
#
# Usage:
#   ./opr_list_to_lua.sh army_export.txt                # writes opr_profile_assigner.lua
#   ./opr_list_to_lua.sh army_export.txt my_output.lua   # custom output name
#
# Expects each unit as a two-line block, blank-line separated:
#   [Nx ]Unit Name [size] Q#+ D#+ | ###pts | rule, rule, ...
#   weapon, weapon, ...
# which is the standard Army Forge "text export" format.
# ==============================================================

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <army_export.txt> [output.lua]" >&2
  exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="${2:-opr_profile_assigner.lua}"

if [[ ! -f "$INPUT_FILE" ]]; then
  echo "Error: input file '$INPUT_FILE' not found" >&2
  exit 1
fi

# Escapes double quotes / backslashes so extracted text is safe to
# drop straight into a Lua "..." string literal.
lua_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

# Matches:  [Nx ]Name [size] Q#+ D#+ | ###pts | rules
# Groups:     2   3     4     5   6    7      8
STAT_RE='^(([0-9]+)x )?(.+) \[([0-9]+)\] Q([0-9]+)\+ D([0-9]+)\+ \| ([0-9]+)pts \| (.+)$'

ARMY_HEADER=""
entries=""

unit_name=""
squad_size=""
instance_count=""
quality=""
defense=""
points=""
rules_raw=""
equipment=""

build_entry() {
  local tough=""
  if [[ "$rules_raw" =~ Tough\(([0-9]+)\) ]]; then
    tough="${BASH_REMATCH[1]}"
  fi

  # Tough(N) gets folded into the stats line instead, so drop it
  # from the rules list to avoid saying it twice.
  local rules_clean
  rules_clean="$(printf '%s' "$rules_raw" | sed -E 's/,? *Tough\([0-9]+\)//; s/^, *//; s/, *$//')"

  local stats="Quality ${quality}+ | Defense ${defense}+"
  if [[ -n "$tough" ]]; then
    stats="${stats} | Tough ${tough}"
  fi

  local rules_full="$rules_clean"
  if [[ -n "$equipment" ]]; then
    if [[ -n "$rules_full" ]]; then
      rules_full="${rules_full}. Equipment: ${equipment}"
    else
      rules_full="Equipment: ${equipment}"
    fi
  fi

  local name_esc stats_esc rules_esc
  name_esc="$(lua_escape "$unit_name")"
  stats_esc="$(lua_escape "$stats")"
  rules_esc="$(lua_escape "$rules_full")"

  printf '  -- %sx unit(s), %s model(s) each | %spts\n  ["%s"] = {\n    stats = "%s",\n    rules = "%s",\n  },\n' \
    "${instance_count:-1}" "$squad_size" "$points" "$name_esc" "$stats_esc" "$rules_esc"
}

reset_block() {
  unit_name=""; squad_size=""; instance_count=""; quality=""
  defense=""; points=""; rules_raw=""; equipment=""
}

while IFS= read -r line || [[ -n "$line" ]]; do
  if [[ -z "$line" ]]; then
    if [[ -n "$unit_name" ]]; then
      entries+="$(build_entry)"$'\n'
      reset_block
    fi
    continue
  fi

  if [[ "$line" =~ ^\+\+ ]]; then
    ARMY_HEADER="$line"
    continue
  fi

  if [[ -z "$unit_name" && "$line" =~ $STAT_RE ]]; then
    instance_count="${BASH_REMATCH[2]}"
    unit_name="${BASH_REMATCH[3]}"
    squad_size="${BASH_REMATCH[4]}"
    quality="${BASH_REMATCH[5]}"
    defense="${BASH_REMATCH[6]}"
    points="${BASH_REMATCH[7]}"
    rules_raw="${BASH_REMATCH[8]}"
    continue
  fi

  # Any other non-blank line while a unit block is open is equipment text.
  if [[ -n "$unit_name" ]]; then
    if [[ -n "$equipment" ]]; then
      equipment+=", $line"
    else
      equipment="$line"
    fi
  fi
done < "$INPUT_FILE"

# Flush the last block if the file doesn't end on a blank line.
if [[ -n "$unit_name" ]]; then
  entries+="$(build_entry)"$'\n'
fi

if [[ -z "$entries" ]]; then
  echo "Error: no units matched the expected export format. Is this a text export from Army Forge?" >&2
  exit 1
fi

ARMY_HEADER_ESC="$(lua_escape "${ARMY_HEADER:-unknown source}")"

# ---- Write the file: static header, generated table, static rest ----

cat > "$OUTPUT_FILE" << HEADER_EOF
-- ============================================================
-- OPR Unit Profile Assigner — Global script, generated by opr_list_to_lua.sh
-- Source list: ${ARMY_HEADER_ESC}
--
-- What this does:
--   - Right-click any unassigned model -> pick a unit from the list
--     to assign it. Assignment INJECTS a self-contained script into
--     that specific model (via setLuaScript + reload), so the model
--     keeps working — name, tooltip, wound tracking — even if you
--     save it individually and load it into a totally different
--     game with no Global script at all.
--   - Once assigned, a model manages itself: its own right-click
--     menu ("Take Wound" / "Heal Wound", applying to your whole
--     current selection) lives in ITS OWN script from that point on.
--   - The model's Name field shows the unit name, Quality/Defense,
--     and current/max Tough, all colored via TTS's own BBCode —
--     visible without even hovering. The tooltip (hover) adds the
--     full stat line, abilities, and equipment.
--   - This Global script's only ongoing job is offering the unit
--     list to models that don't have a script yet.
--
-- Install:
--   Right-click the table -> Scripting -> Lua Script -> paste this
--   in, then Save & Play. (If TTS says "no save found", create a
--   save via Games -> Save & Load -> Create first, then re-save
--   the script — see previous notes on that.)
--
-- Note on models assigned under an earlier version of this script:
--   Those models never got their own script, so they'll show up as
--   "unassigned" here again — just right-click and pick their unit
--   once more to bring them onto this version.
--
-- Regenerate:
--   Re-run opr_list_to_lua.sh whenever your list changes, rather
--   than hand-editing UNIT_PROFILES below.
-- ============================================================

-- Set true if you only want the menu added to objects tagged
-- "Figurine" (most official minis/tokens carry that tag).
local ONLY_FIGURINES = false

local UNIT_PROFILES = {
HEADER_EOF

printf '%s' "$entries" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'FOOTER_EOF'
}

local function getToughMax(unitKey)
  local profile = UNIT_PROFILES[unitKey]
  if not profile then return nil end
  return tonumber(string.match(profile.stats, "Tough (%d+)"))
end

-- Escapes a string so it's safe to drop into a Lua "..." literal
-- inside the per-model script template.
local function luaStringEscape(s)
  s = s:gsub("\\", "\\\\")
  s = s:gsub('"', '\\"')
  return s
end

-- Escapes a string so gsub treats it as literal replacement text
-- rather than interpreting "%" as a capture-group reference.
local function gsubSafe(s)
  return (s:gsub("%%", "%%%%"))
end

-- ===== Self-contained per-model script template =====
-- Everything an assigned model needs to run entirely on its own:
-- its stat block, its wound tracking, its own menu. @@TOKEN@@
-- placeholders get filled in per-unit in buildPerModelScript.

local PER_MODEL_SCRIPT_TEMPLATE = [==[
-- Self-contained OPR model script — generated by opr_profile_assigner.lua
-- Portable: this object keeps working (name, tooltip, wound tracking)
-- even when saved individually and loaded into a different game,
-- because everything it needs lives in this script and its memo.

local UNIT_NAME = "@@UNIT_NAME@@"
local STATS = "@@STATS@@"
local RULES = "@@RULES@@"
local TOUGH_MAX = @@TOUGH_MAX@@

-- ===== Text helpers =====

-- Splits a comma-separated string on TOP-LEVEL commas only, so a
-- weapon like "Energy Sword (A6, AP(1), Rending)" stays one item
-- instead of shattering on the commas inside its own parentheses.
local function splitTopLevelCommas(s)
  local items = {}
  local depth = 0
  local start = 1
  for i = 1, #s do
    local c = s:sub(i, i)
    if c == "(" then depth = depth + 1
    elseif c == ")" then depth = depth - 1
    elseif c == "," and depth == 0 then
      table.insert(items, s:sub(start, i - 1))
      start = i + 1
    end
  end
  table.insert(items, s:sub(start))
  for i, item in ipairs(items) do
    items[i] = item:match("^%s*(.-)%s*$")
  end
  return items
end

-- Pulls the equipment list out of RULES (if present) as a table of
-- individual items, separate from the ability/special-rule text.
local function splitAbilitiesAndEquipment()
  local abilities, equipStr = RULES:match("^(.-)%s*Equipment:%s*(.+)$")
  if not equipStr then
    return RULES, nil
  end
  abilities = abilities:gsub("%.%s*$", "")
  abilities = abilities:match("^%s*(.-)%s*$")
  return abilities, splitTopLevelCommas(equipStr)
end

-- Colored via TTS's own BBCode ([hexcolor]text[-]), which works
-- directly in the Name field and tooltips — no UI panel needed.
-- White text just uses no color tag at all rather than [ffffff].
local Q_COLOR = "ef4444"     -- red-orange, for Quality
local D_COLOR = "0ea5e9"     -- sky blue, for Defense
local TOUGH_COLOR = "2ecc40" -- green, for current and max Tough
local RULES_COLOR = "3498db" -- blue

-- Name field: bold unit name, then Quality/Defense, then a
-- "Tough: current / max" line (only if this unit has Tough) — all
-- visible without hovering.
local function buildNameLabel(tough)
  local q, d = STATS:match("Quality (%d+)%+.-Defense (%d+)%+")
  local label = "[b]" .. UNIT_NAME .. "[/b]"
  if q and d then
    label = label ..
      "\n[" .. Q_COLOR .. "][b]Q" .. q .. "[/b]+[-]" ..
      " / " ..
      "[" .. D_COLOR .. "][b]D" .. d .. "[/b]+[-]"
  end
  if TOUGH_MAX > 0 then
    label = label ..
      "\n[b]Tough: [" .. TOUGH_COLOR .. "]" .. tough .. "[/b][-]" ..
      " / " ..
      "[b][" .. TOUGH_COLOR .. "]" .. TOUGH_MAX .. "[/b][-]"
  end
  return label
end

-- Tooltip (hover): full stats line, abilities, equipment list. White
-- text (stats, equipment) uses no color tag at all.
local function formatDescription()
  local abilities, equipItems = splitAbilitiesAndEquipment()
  local lines = {}
  table.insert(lines, STATS)
  table.insert(lines, "[" .. RULES_COLOR .. "]" .. abilities .. "[-]")
  if equipItems then
    table.insert(lines, "Equipment:")
    for _, item in ipairs(equipItems) do
      table.insert(lines, "     " .. item)
    end
  end
  return table.concat(lines, "\n")
end

-- Memo just stores the current Tough count as a plain number.
local function parseMemo(memo)
  local tough = tonumber(memo)
  if not tough then tough = TOUGH_MAX end
  return tough
end

-- Global (not local) so other models can invoke it via .call() when
-- you apply Take/Heal Wound to a multi-selected group.
function adjustWound(params)
  local delta = (params and params.delta) or 0
  local tough = parseMemo(self.memo)
  tough = math.max(0, math.min(TOUGH_MAX, tough + delta))
  self.memo = tostring(tough)
  self.setName(buildNameLabel(tough))
end

local function forSelectedOrSelf(player_color, fn)
  local selected = Player[player_color].getSelectedObjects()
  if #selected > 0 then
    for _, o in ipairs(selected) do fn(o) end
  else
    fn(self)
  end
end

local function buildMenu()
  self.clearContextMenu()
  if TOUGH_MAX > 0 then
    self.addContextMenuItem("Take Wound", function(player_color)
      forSelectedOrSelf(player_color, function(o)
        o.call('adjustWound', { delta = -1 })
      end)
    end)
    self.addContextMenuItem("Heal Wound", function(player_color)
      forSelectedOrSelf(player_color, function(o)
        o.call('adjustWound', { delta = 1 })
      end)
    end)
  end
end

function onLoad()
  local tough = parseMemo(self.memo)
  self.setName(buildNameLabel(tough))
  self.setDescription(formatDescription())
  buildMenu()
end
]==]

local function buildPerModelScript(unitKey)
  local profile = UNIT_PROFILES[unitKey]
  if not profile then return nil end
  local toughMax = getToughMax(unitKey) or 0

  local script = PER_MODEL_SCRIPT_TEMPLATE
  script = script:gsub("@@UNIT_NAME@@", gsubSafe(luaStringEscape(unitKey)))
  script = script:gsub("@@STATS@@", gsubSafe(luaStringEscape(profile.stats)))
  script = script:gsub("@@RULES@@", gsubSafe(luaStringEscape(profile.rules)))
  script = script:gsub("@@TOUGH_MAX@@", tostring(toughMax))
  return script
end

-- ===== Assignment =====

local function assignProfile(obj, unitKey)
  local script = buildPerModelScript(unitKey)
  if not script then return end
  local toughMax = getToughMax(unitKey) or 0
  obj.memo = tostring(toughMax)
  obj.setLuaScript(script)
  obj.reload()
end

local function forSelectedOrSelf(player_color, fallbackObj, fn)
  local selected = Player[player_color].getSelectedObjects()
  if #selected > 0 then
    for _, o in ipairs(selected) do fn(o) end
  else
    fn(fallbackObj)
  end
end

-- ===== Menu wiring (unassigned models only) =====
-- An object with its own script already installed (getLuaScript() is
-- non-empty) manages its own menu from here on, so this only ever
-- touches models that haven't been assigned yet.

local function attachUnassignedMenu(object)
  if ONLY_FIGURINES and not object.hasTag("Figurine") then return end
  local existingScript = object.getLuaScript()
  if existingScript and existingScript ~= "" then return end

  object.clearContextMenu()
  for unitKey, _ in pairs(UNIT_PROFILES) do
    object.addContextMenuItem(unitKey, function(player_color)
      forSelectedOrSelf(player_color, object, function(o)
        assignProfile(o, unitKey)
      end)
    end)
  end
end

-- Covers models already on the table when the save loads...
function onLoad()
  for _, obj in ipairs(getAllObjects()) do
    attachUnassignedMenu(obj)
  end
end

-- ...and models spawned afterward (from a bag, spawnObject, etc.)
function onObjectSpawn(object)
  attachUnassignedMenu(object)
end
FOOTER_EOF

unit_count="$(grep -c '^  \[' "$OUTPUT_FILE" || true)"
echo "Wrote ${unit_count} unit profile(s) to ${OUTPUT_FILE}"
