-- ============================================================
-- OPR Unit Profile Assigner — Global script, generated by opr_list_to_lua.sh
-- Source list: ++ HDF Into The Frontier - Human Defense Force (v3.5.3) [GFSQAI 1190pts] [15 Units] ++
--
-- What this does:
--   - Right-click any unassigned model -> pick a unit from the list
--     to assign it. Assignment INJECTS a self-contained script into
--     that specific model (via setLuaScript + reload), so the model
--     keeps working — name, tooltip, wound tracking — even if you
--     save it individually and load it into a totally different
--     game with no Global script at all.
--   - Once assigned, a model manages itself: its own right-click
--     menu ("Take Wound" / "Heal Wound", applying to your whole
--     current selection) lives in ITS OWN script from that point on.
--   - The model's Name field shows the unit name, Quality/Defense,
--     and current/max Tough, all colored via TTS's own BBCode —
--     visible without even hovering. The tooltip (hover) adds the
--     full stat line, abilities, and equipment.
--   - This Global script's only ongoing job is offering the unit
--     list to models that don't have a script yet.
--
-- Install:
--   Right-click the table -> Scripting -> Lua Script -> paste this
--   in, then Save & Play. (If TTS says "no save found", create a
--   save via Games -> Save & Load -> Create first, then re-save
--   the script — see previous notes on that.)
--
-- Note on models assigned under an earlier version of this script:
--   Those models never got their own script, so they'll show up as
--   "unassigned" here again — just right-click and pick their unit
--   once more to bring them onto this version.
--
-- Regenerate:
--   Re-run opr_list_to_lua.sh whenever your list changes, rather
--   than hand-editing UNIT_PROFILES below.
-- ============================================================

-- Set true if you only want the menu added to objects tagged
-- "Figurine" (most official minis/tokens carry that tag).
local ONLY_FIGURINES = false

local UNIT_PROFILES = {
  -- 3x unit(s), 3 model(s) each | 35pts
  ["Infantry Squad"] = {
    stats = "Quality 5+ | Defense 5+",
    rules = "3x Hold the Line. Equipment: 3x Rifle (24\", A1), 3x CCW (A1)",
  },
  -- 3x unit(s), 1 model(s) each | 50pts
  ["Veteran"] = {
    stats = "Quality 4+ | Defense 5+ | Tough 3",
    rules = "Hold the Line. Equipment: Rifle (24\", A3), CCW (A3)",
  },
  -- 3x unit(s), 1 model(s) each | 55pts
  ["GRUNT Robot"] = {
    stats = "Quality 5+ | Defense 5+ | Tough 3",
    rules = "Fearless, Good Shot, Hold the Line. Equipment: Rifle (24\", A3), CCW (A3)",
  },
  -- 1x unit(s), 1 model(s) each | 105pts
  ["Company Leader"] = {
    stats = "Quality 4+ | Defense 5+ | Tough 9",
    rules = "Hero, Hold the Line. Equipment: Master Pistol (12\", A6), CCW (A6)",
  },
  -- 1x unit(s), 1 model(s) each | 115pts
  ["Drill Sergeant"] = {
    stats = "Quality 4+ | Defense 5+ | Tough 9",
    rules = "Hero, Hold the Line, Bane in Melee Buff. Equipment: Master Pistol (12\", A6), CCW (A6)",
  },
  -- 1x unit(s), 1 model(s) each | 125pts
  ["Enforcer"] = {
    stats = "Quality 4+ | Defense 5+ | Tough 9",
    rules = "Hero, Hold the Line, No Retreat Buff. Equipment: Master Pistol (12\", A6), CCW (A6)",
  },
  -- 1x unit(s), 1 model(s) each | 125pts
  ["Weapon Team"] = {
    stats = "Quality 5+ | Defense 5+ | Tough 9",
    rules = "Hold the Line. Equipment: Mortar (30\", A3, Blast(3), Indirect), Crew (A6)",
  },
  -- 1x unit(s), 1 model(s) each | 135pts
  ["Colonel Rixxon"] = {
    stats = "Quality 4+ | Defense 5+ | Tough 9",
    rules = "Hero, Unique, Hold the Line, Morale Debuff. Equipment: Master Pistol (12\", A6), Energy Sword (A6, AP(1), Rending)",
  },
  -- 1x unit(s), 1 model(s) each | 165pts
  ["OGRE Robot"] = {
    stats = "Quality 4+ | Defense 4+ | Tough 9",
    rules = "Fearless, Furious, Hold the Line. Equipment: OGRE Gatling Gun (12\", A9, AP(1)), Heavy CCW (A3, AP(1))",
  },
}

local function getToughMax(unitKey)
  local profile = UNIT_PROFILES[unitKey]
  if not profile then return nil end
  return tonumber(string.match(profile.stats, "Tough (%d+)"))
end

-- Escapes a string so it's safe to drop into a Lua "..." literal
-- inside the per-model script template.
local function luaStringEscape(s)
  s = s:gsub("\\", "\\\\")
  s = s:gsub('"', '\\"')
  return s
end

-- Escapes a string so gsub treats it as literal replacement text
-- rather than interpreting "%" as a capture-group reference.
local function gsubSafe(s)
  return (s:gsub("%%", "%%%%"))
end

-- ===== Self-contained per-model script template =====
-- Everything an assigned model needs to run entirely on its own:
-- its stat block, its wound tracking, its own menu. @@TOKEN@@
-- placeholders get filled in per-unit in buildPerModelScript.

local PER_MODEL_SCRIPT_TEMPLATE = [==[
-- Self-contained OPR model script — generated by opr_profile_assigner.lua
-- Portable: this object keeps working (name, tooltip, wound tracking)
-- even when saved individually and loaded into a different game,
-- because everything it needs lives in this script and its memo.

local UNIT_NAME = "@@UNIT_NAME@@"
local STATS = "@@STATS@@"
local RULES = "@@RULES@@"
local TOUGH_MAX = @@TOUGH_MAX@@

-- ===== Text helpers =====

-- Splits a comma-separated string on TOP-LEVEL commas only, so a
-- weapon like "Energy Sword (A6, AP(1), Rending)" stays one item
-- instead of shattering on the commas inside its own parentheses.
local function splitTopLevelCommas(s)
  local items = {}
  local depth = 0
  local start = 1
  for i = 1, #s do
    local c = s:sub(i, i)
    if c == "(" then depth = depth + 1
    elseif c == ")" then depth = depth - 1
    elseif c == "," and depth == 0 then
      table.insert(items, s:sub(start, i - 1))
      start = i + 1
    end
  end
  table.insert(items, s:sub(start))
  for i, item in ipairs(items) do
    items[i] = item:match("^%s*(.-)%s*$")
  end
  return items
end

-- Pulls the equipment list out of RULES (if present) as a table of
-- individual items, separate from the ability/special-rule text.
local function splitAbilitiesAndEquipment()
  local abilities, equipStr = RULES:match("^(.-)%s*Equipment:%s*(.+)$")
  if not equipStr then
    return RULES, nil
  end
  abilities = abilities:gsub("%.%s*$", "")
  abilities = abilities:match("^%s*(.-)%s*$")
  return abilities, splitTopLevelCommas(equipStr)
end

-- Colored via TTS's own BBCode ([hexcolor]text[-]), which works
-- directly in the Name field and tooltips — no UI panel needed.
-- White text just uses no color tag at all rather than [ffffff].
local Q_COLOR = "ef4444"     -- red-orange, for Quality
local D_COLOR = "0ea5e9"     -- sky blue, for Defense
local TOUGH_COLOR = "2ecc40" -- green, for current and max Tough
local RULES_COLOR = "3498db" -- blue

-- Name field: bold unit name, then Quality/Defense, then a
-- "Tough: current / max" line (only if this unit has Tough) — all
-- visible without hovering.
local function buildNameLabel(tough)
  local q, d = STATS:match("Quality (%d+)%+.-Defense (%d+)%+")
  local label = "[b]" .. UNIT_NAME .. "[/b]"
  if q and d then
    label = label ..
      "\n[" .. Q_COLOR .. "][b]Q" .. q .. "[/b]+[-]" ..
      " / " ..
      "[" .. D_COLOR .. "][b]D" .. d .. "[/b]+[-]"
  end
  if TOUGH_MAX > 0 then
    label = label ..
      "\n[b]Tough: [" .. TOUGH_COLOR .. "]" .. tough .. "[/b][-]" ..
      " / " ..
      "[b][" .. TOUGH_COLOR .. "]" .. TOUGH_MAX .. "[/b][-]"
  end
  return label
end

-- Tooltip (hover): full stats line, abilities, equipment list. White
-- text (stats, equipment) uses no color tag at all.
local function formatDescription()
  local abilities, equipItems = splitAbilitiesAndEquipment()
  local lines = {}
  table.insert(lines, STATS)
  table.insert(lines, "[" .. RULES_COLOR .. "]" .. abilities .. "[-]")
  if equipItems then
    table.insert(lines, "Equipment:")
    for _, item in ipairs(equipItems) do
      table.insert(lines, "     " .. item)
    end
  end
  return table.concat(lines, "\n")
end

-- Memo just stores the current Tough count as a plain number.
local function parseMemo(memo)
  local tough = tonumber(memo)
  if not tough then tough = TOUGH_MAX end
  return tough
end

-- ===== Range measuring =====

-- TTS's default table scale is 1 world unit = 1 inch. If your table/
-- minis use a different scale, adjust this to calibrate.
local INCHES_PER_UNIT = 1

-- Plain gsub, not a lazy-match pattern, so it's safe under MoonSharp's
-- pattern-complexity limit (see project notes).
local function trim(s)
  s = s:gsub("^%s+", "")
  s = s:gsub("%s+$", "")
  return s
end

-- Estimates a round base's radius (in inches) from its axis-aligned
-- bounding box: for a circular base the box is a square of side
-- 2*radius in the x/z plane, so this holds up under rotation.
local function getBaseRadiusInches(obj)
  local bounds = obj.getBounds()
  if not bounds or not bounds.size then return 0 end
  return ((bounds.size.x + bounds.size.z) / 4) * INCHES_PER_UNIT
end

-- Base-edge to base-edge distance, not center to center: OPR measures
-- range from the edge of the model's base, so this subtracts both
-- models' estimated base radii from the raw center-to-center distance.
local function getDistanceInches(a, b)
  local pa, pb = a.getPosition(), b.getPosition()
  local dx, dz = pa.x - pb.x, pa.z - pb.z
  local centerDist = math.sqrt(dx * dx + dz * dz) * INCHES_PER_UNIT
  local edgeDist = centerDist - getBaseRadiusInches(a) - getBaseRadiusInches(b)
  return math.max(0, edgeDist)
end

-- Parses this model's equipment (e.g. `Rifle (24", A3)`, `CCW (A2)`)
-- into {name, range} pairs. range is nil for melee weapons (no `"`
-- value present), which OPR resolves in base contact rather than by
-- range check.
local function getWeaponRanges()
  local _, equipItems = splitAbilitiesAndEquipment()
  local weapons = {}
  if not equipItems then return weapons end
  for _, item in ipairs(equipItems) do
    local openIdx = item:find("(", 1, true)
    local name = item
    local range = nil
    if openIdx then
      name = trim(item:sub(1, openIdx - 1))
      local closeIdx = item:find(")", openIdx, true)
      local inside = item:sub(openIdx + 1, (closeIdx or (#item + 1)) - 1)
      local firstToken = splitTopLevelCommas(inside)[1] or ""
      local quoteIdx = firstToken:find("\"", 1, true)
      if quoteIdx then
        range = tonumber(trim(firstToken:sub(1, quoteIdx - 1)))
      end
    end
    table.insert(weapons, { name = name, range = range })
  end
  return weapons
end

-- Reports this model's distance to each target and whether each of
-- its ranged weapons can reach it.
local function measureRangeReport(targets)
  local weapons = getWeaponRanges()
  local lines = {}
  for _, target in ipairs(targets) do
    local dist = getDistanceInches(self, target)
    local targetName = target.getName()
    if targetName == "" then targetName = "target" end
    table.insert(lines, UNIT_NAME .. " -> " .. targetName .. ": " .. string.format("%.1f", dist) .. "\"")
    for _, w in ipairs(weapons) do
      if w.range then
        local status = dist <= w.range and "IN RANGE" or "out of range"
        table.insert(lines, "   " .. w.name .. " (" .. w.range .. "\"): " .. status)
      else
        table.insert(lines, "   " .. w.name .. " (melee)")
      end
    end
  end
  return table.concat(lines, "\n")
end

-- Global (not local) so other models can invoke it via .call() when
-- you apply Take/Heal Wound to a multi-selected group.
function adjustWound(params)
  local delta = (params and params.delta) or 0
  local tough = parseMemo(self.memo)
  tough = math.max(0, math.min(TOUGH_MAX, tough + delta))
  self.memo = tostring(tough)
  self.setName(buildNameLabel(tough))
end

local function forSelectedOrSelf(player_color, fn)
  local selected = Player[player_color].getSelectedObjects()
  if #selected > 0 then
    for _, o in ipairs(selected) do fn(o) end
  else
    fn(self)
  end
end

local function buildMenu()
  self.clearContextMenu()
  if TOUGH_MAX > 0 then
    self.addContextMenuItem("Take Wound", function(player_color)
      forSelectedOrSelf(player_color, function(o)
        o.call('adjustWound', { delta = -1 })
      end)
    end)
    self.addContextMenuItem("Heal Wound", function(player_color)
      forSelectedOrSelf(player_color, function(o)
        o.call('adjustWound', { delta = 1 })
      end)
    end)
  end
  self.addContextMenuItem("Measure Range", function(player_color)
    local selected = Player[player_color].getSelectedObjects()
    local targets = {}
    for _, o in ipairs(selected) do
      if o.getGUID() ~= self.getGUID() then table.insert(targets, o) end
    end
    if #targets == 0 then
      broadcastToColor("Measure Range: select one or more target models first, then right-click this model and choose Measure Range again.", player_color, {1, 0.4, 0.4})
      return
    end
    broadcastToColor(measureRangeReport(targets), player_color, {1, 1, 1})
  end)
end

function onLoad()
  local tough = parseMemo(self.memo)
  self.setName(buildNameLabel(tough))
  self.setDescription(formatDescription())
  buildMenu()
end
]==]

local function buildPerModelScript(unitKey)
  local profile = UNIT_PROFILES[unitKey]
  if not profile then return nil end
  local toughMax = getToughMax(unitKey) or 0

  local script = PER_MODEL_SCRIPT_TEMPLATE
  script = script:gsub("@@UNIT_NAME@@", gsubSafe(luaStringEscape(unitKey)))
  script = script:gsub("@@STATS@@", gsubSafe(luaStringEscape(profile.stats)))
  script = script:gsub("@@RULES@@", gsubSafe(luaStringEscape(profile.rules)))
  script = script:gsub("@@TOUGH_MAX@@", tostring(toughMax))
  return script
end

-- ===== Assignment =====

local function assignProfile(obj, unitKey)
  local script = buildPerModelScript(unitKey)
  if not script then return end
  local toughMax = getToughMax(unitKey) or 0
  obj.memo = tostring(toughMax)
  obj.setLuaScript(script)
  obj.reload()
end

local function forSelectedOrSelf(player_color, fallbackObj, fn)
  local selected = Player[player_color].getSelectedObjects()
  if #selected > 0 then
    for _, o in ipairs(selected) do fn(o) end
  else
    fn(fallbackObj)
  end
end

-- ===== Menu wiring (unassigned models only) =====
-- An object with its own script already installed (getLuaScript() is
-- non-empty) manages its own menu from here on, so this only ever
-- touches models that haven't been assigned yet.

local function attachUnassignedMenu(object)
  if ONLY_FIGURINES and not object.hasTag("Figurine") then return end
  local existingScript = object.getLuaScript()
  if existingScript and existingScript ~= "" then return end

  object.clearContextMenu()
  for unitKey, _ in pairs(UNIT_PROFILES) do
    object.addContextMenuItem(unitKey, function(player_color)
      forSelectedOrSelf(player_color, object, function(o)
        assignProfile(o, unitKey)
      end)
    end)
  end
end

-- Covers models already on the table when the save loads...
function onLoad()
  for _, obj in ipairs(getAllObjects()) do
    attachUnassignedMenu(obj)
  end
end

-- ...and models spawned afterward (from a bag, spawnObject, etc.)
function onObjectSpawn(object)
  attachUnassignedMenu(object)
end
